### ISSUE TITLE
The disassembly/Code tabs are not viewing anything. 

### ISSUE THREAD

**Issue by eddsanity** [Satharus/Disass#3]
I am not sure whether I am not using it properly or if it's an actual bug but I tried disassembling a C code with `disas main` and I only get output in the GDB output tab. The other 2 tabs are completely empty. I am not sure whether this is an actual bug or I am just not using it properly. Might work on it as soon as my exams are over

**Comment by Satharus** [comment]
Thanks for checking Disass!
First of all, sorry for the late reply as I've been busy with exams and I haven't opened GitHub in a few days.

If you ran the software from the command line using  ```./Disass main```,
You should first set a breakpoint from here: 
![image](https://user-images.githubusercontent.com/29730368/58055032-c4c58f00-7b5c-11e9-9552-d1e56e8dd223.png)
For example: If you wanted to break at the start of the main function, you'd type in ```main``` and then click on the break button.

After that you should run the program using the run button, as well as passing any command line arguments you need.
![image](https://user-images.githubusercontent.com/29730368/58055089-ee7eb600-7b5c-11e9-861c-0af931bce1c3.png)

Please tell me how it works, I will soon add a "how to use" tab and try to make the program a little more intuitive.
Your contributions will be more than welcome, of course :D!

Edit:
There's a bug I just discovered where the file architecture doesn't appear if you run the program from the command line and send the program to be disassembled as an argument.
I fixed it but it isn't added to the release for now, I'll add it to the next release. If you want to try it, run the project itself (Using Qt Creator) not the AppImage.

This bug however, shouldn't affect the Disassembly and Code tabs not showing anything. That just meant that you were running the program without setting a break point, I suppose.

Side Note: If you want the code tab to contain the source code you have to add the argument ```-ggdb``` when compiling the C/C++ code using ```gcc``` or ```g++```. All that tab does is read the code from the running GDB instance, it doesn't translate the assembly code into C. So if the code itself isn't provided by the compiler, it won't work.

**Comment by eddsanity** [comment]
I think I was setting a break point, though. I am sure I was setting it to main and I did that multiple times. I'll try again though maybe my memory is distorted. I'll let you know as soon as my exams are over
